### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by reiz** [75lb/grunt-jsdoc-to-markdown#2]
Under which license is this software? MIT?

**Comment by 75lb** [comment]
software now carries MIT license https://github.com/75lb/grunt-jsdoc-to-markdown/commit/84b0f0073dbecf73a07e05d11a49cdf768e30821

**Comment by reiz** [comment]
Awesome! Thanks :+1:

**Comment by 75lb** [comment]
fyi, i'm looking for feedback on the next version, if you have some time ;)

Install it:
`$ npm install -g jsdoc-to-markdown@next`

take a look at the new options:
`$ jsdoc2md --help`

I'm still working on it, and documentation for all the new stuff..
